apiVersion: v1
kind: ConfigMap
data: |
    name: platinum-tests-suite
    tests:
    - id: 1
      manifest: ./manifests/malicious-pod.yaml
      assert:
        fieldSelectors:
          metadata.name: malicious-pod
          metadata.namespace: platinum-tests
        count: 0

    - id: 2
      manifest: ./manifests/network-policy.yaml
      assert:
        fieldSelectors:
          metadata.name: test-network-policy
          metadata.namespace: platinum-tests
          status: error
        count: 0
#Strategy 1 for each manifests, deploy the resources, tests, teardown. (Single)
#Strategy 2 deploy the resources, tests them all and tear down everything (Multiple)