apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tests.go-kubetest.io
spec:
  group: go-kubetest.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  resources:
                    type: array
                    items:
                      type: string
                  setup:
                    type: object
                    properties:
                      waitFor:
                        type: array
                        items:
                          type: object
                          properties:
                            resource:
                              type: string
                            timeout:
                              type: string
                        required:
                        - resource
                        - timeout
                  assert:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                        resource:
                          type: string
                        timeout:
                          type: string
                        count:
                          type: integer
                        errors:
                          type: array
                          items:
                            type: string
                        selectors:
                          x-kubernetes-preserve-unknown-fields: true
                  teardown:
                    type: object
                    properties:
                      waitFor:
                        type: array
                        items:
                          type: object
                          properties:
                            resource:
                              type: string
                            timeout:
                              type: string
                required:
                - setup
                - assert
                - teardown
  scope: Namespaced
  names:
    plural: tests
    singular: test
    kind: TestDefinition
    shortNames:
    - td
