apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tests.go-kubetest.io
spec:
  group: go-kubetest.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
                  resources:
                    type: array
                    items:
                      type: string
                  setup:
                    type: object
                    properties:
                      waitFor:
                        type: array
                        items:
                          type: object
                          properties:
                            resource:
                              type: string
                            timeout:
                              type: string
                          required:
                          - resource
                          - timeout
                  assert:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
                        type:
                          type: string
                          pattern: '^(expectedResources|expectedErrors)$'
                        resource:
                          type: string
                        timeout:
                          type: string
                        count:
                          type: integer
                        errors:
                          type: array
                          items:
                            type: string
                        selectors:
                          x-kubernetes-preserve-unknown-fields: true
                      required:
                      - type
                      - name
                  teardown:
                    type: object
                    properties:
                      waitFor:
                        type: array
                        items:
                          type: object
                          properties:
                            resource:
                              type: string
                            timeout:
                              type: string
                required:
                - name
                - resources
                - setup
                - assert
                - teardown

  scope: Namespaced
  names:
    plural: tests
    singular: test
    kind: TestDefinition
    shortNames:
    - tdef
