apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testresources.go-kubetest.io
spec:
  group: go-kubetest.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                data:
                  x-kubernetes-preserve-unknown-fields: true
              required:
              - data
  scope: Namespaced
  names:
    plural: testresources
    singular: testresource
    kind: TestResource
    shortNames:
    - trsc
