apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testresults.go-kubetest.io
spec:
  group: go-kubetest.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                result:
                  type: boolean
                assertions:
                  x-kubernetes-preserve-unknown-fields: true
              required:
              - result
              - assertions
      additionalPrinterColumns:
      - name: Result
        type: boolean
        description: The result of the test
        jsonPath: .spec.result

  scope: Namespaced
  names:
    plural: testresults
    singular: testresult
    kind: TestResult
    shortNames:
    - tres
