apiVersion: go-kubetest.io/v1
kind: TestDefinition
metadata:
  name: my-test-definition
spec:
  - name: namespace_creation_0
    manifest: namespaces
    setup:
      waitFor:
      - resource: v1/Namespace/namespace-1
        timeout: 120s
    assert:
    - type: expectedErrors
      errors: []
    - type: expectedResources
      apiVersion: v1
      kind: Namespace
      count: 1
      selectors:
        metadata.name: namespace-1
        status.phase: Active
        metadata.labels.myCustomLabel: myCustomValue
    teardown:
      waitFor:
      - resource: v1/Namespace/namespace-1
        timeout: 120s
