apiVersion: go-kubetest.io/v1
kind: TestDefinition
metadata:
  name: namespaces
  labels:
    type: hard
spec:
  resources:
  - namespaces
  setup:
    waitFor:
    - resource: v1:Namespace:namespace-1
      timeout: 120s
    - resource: v1:Namespace:namespace-2
      timeout: 120s
  assert:
  - name: count-namespaces
    type: expectedResources
    resource: v1:Namespace
    timeout: 120s
    count: 2
    selectors:
      status.phase: Active
      metadata.labels.myCustomLabel: myCustomValue
  teardown:
    waitFor:
    - resource: v1:Namespace:namespace-1
      timeout: 120s
    - resource: v1:Namespace:namespace-2
      timeout: 120s
