apiVersion: go-kubetest.io/v1
kind: TestResource
metadata:
  name: namespaces
spec:
  data: |
    apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        myCustomLabel: myCustomValue
      name: namespace-1
    spec: {}
    status: {}
    ---
    apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        myCustomLabel: myCustomValue
      name: namespace-2
    spec: {}
    status: {}

# Below resources are not used
---
apiVersion: go-kubetest.io/v1
kind: TestResource
metadata:
  name: deployment
spec:
  data: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
      labels:
        app: nginx
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
            - containerPort: 80
---
apiVersion: go-kubetest.io/v1
kind: TestResource
metadata:
  name: pvc
spec:
  data: |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: kubetest-pvc
    spec:
      storageClassName: standard
      claimRef:
        name: kubetest-pvc
        namespace: default